### ISSUE TITLE
Not showing "read-only" message after actions from modals

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-demo#18]
We have the read-only mode on the demo shop, but the "read-only" message is not displayed for POST AJAX requests. Such requests are sent for example when submitting modals with the `.form-async` class, as they are handled by JS. We block those actions and nothing happens but it looks like broken.

**Comment by NyanKiyoshi** [comment]
Maybe the read only response could be a 302 to something like `/dashboard/readonly`, then in the WSGI app, we check if the endpoint is that one, and we render the read only page.

So, with that, we should get the modals redirected to the read only page.

**Comment by NyanKiyoshi** [comment]
@maarcingebala is this issue still true? I have found a asynchronous modal on the customer page, [here](https://demo.getsaleor.com/dashboard/customers/446/), if you add a note, it does show the error message.

Is this good? Or were you referencing another modal at the time you wrote that issue, if you still recall?
