### ISSUE TITLE
Paying with Braintree raise internal error

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-demo#31]
1. Place an [order](https://demo.getsaleor.com/en/order/c4b0122e-3ba1-4d89-a17b-dac9b70f512b/payment/);
1. Pay using Braintree;
1. Should get a 500 error.

**Comment by maarcingebala** [comment]
Braintree was enabled by accident and it wasn't configured properly. I've disabled it and left only the dummy payment option.
